### ISSUE TITLE
Buscar manera de moquear

### ISSUE THREAD

**Issue by FrancoLiberali** [taller2fiuba/hello-world-node#4]

**Comment by FrancoLiberali** [comment]
Los asigno porque yo no lo pude hacer, en la rama meter_mock es lo mas cerca que pude llegar. Meti los controllers y pude hacer test unitario sobre sus metodos, pero no el mock

**Comment by edjus** [comment]
@taller2fiuba/grupo4 ya agregué como usar stubs, spys y mocks, faltaría que @FrancoLiberali remueva lo que está de más y haga el PR
